// TODO: Create function for coercing color tokens as default / light / dark.

import {
  type ColorToken,
  type CssVariable,
  type CssVariableWrapped,
  mapSwatches,
  parseSwatchQuery,
  type SwatchQuery,
  unwrapCssVariable,
} from '../../shared';
import { type Token, token } from '../../styled-system/tokens';

// Because CSS variable names are generated by Panda,
// these functions should not be in /shared.

const CSS_VARIABLES_WRAPPED = Object.fromEntries(
  mapSwatches(({ colorToken }) => [
    [`${colorToken}`, token.var(`colors.${colorToken}` as Token)],
    [`${colorToken}.light`, token.var(`colors.${colorToken}.light` as Token)],
    [`${colorToken}.dark`, token.var(`colors.${colorToken}.dark` as Token)],
  ]).flat(),
) as Record<ColorToken, CssVariableWrapped>;

const CSS_VARIABLES_UNWRAPPED = Object.fromEntries(
  mapSwatches(({ colorToken }) => [
    [`${colorToken}`, unwrapCssVariable(CSS_VARIABLES_WRAPPED[colorToken])],
    [
      `${colorToken}.light`,
      unwrapCssVariable(CSS_VARIABLES_WRAPPED[`${colorToken}.light`]),
    ],
    [
      `${colorToken}.dark`,
      unwrapCssVariable(CSS_VARIABLES_WRAPPED[`${colorToken}.dark`]),
    ],
  ]).flat(),
) as Record<ColorToken, CssVariable>;

export const getColorVariable = (query: SwatchQuery) =>
  CSS_VARIABLES_UNWRAPPED[parseSwatchQuery(query).colorToken];

export const getColorVariableWrapped = (query: SwatchQuery) =>
  CSS_VARIABLES_WRAPPED[parseSwatchQuery(query).colorToken];
